### ISSUE TITLE
Update to 0.97.8

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#307]
There are several changes:

- [x] modals are refactored completely
- [x] tabs have different modes
- [x] chips can be reinitialized (refreshed) - so we can remove this addition from the bridge and use Materialize's implementation
- [x] FABs can transform into a toolbar
- [x] dropdown options bug is fixed (#224)
- [x] test if AMD conversion still works (very likely)
- [x] tabs have selected event built-in, so we can remove our tab-event
- [x] tabs are now supported in navbar
- [x] sidebar changes need to be applied to `md-colors`, also see #313 

And some more which I may have missed for now.

**Comment by hashtonmartyn** [comment]
Installation according to the instructions https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html fails because of the modal refactoring in materialize-css.

**Comment by Thanood** [comment]
Thanks for trying out.. 👍 
They removed leanModal. I'm thinking of a way not to break existing installations.

**Comment by hashtonmartyn** [comment]
No worries, might pay to update the installation instructions to reflect the version requirements until you have a more permanent solution though.

**Comment by Thanood** [comment]
I guess I could just offer an alternative file for v0.97.7 - not sure if I can pass cmd arguments and I'd like to keep it simple.

But I need to redo the modals anyway. It's not initialized on the modal trigger anymore.

**Comment by Thanood** [comment]
@hashtonmartyn Files are updated and tested. Simply replaced `leanModal` with `modal`. 😃 
I've kept the older versions in a subdirectory and updated the docs.

**Comment by hashtonmartyn** [comment]
Nice! That was a fast turn around.

**Comment by Thanood** [comment]
I didn't remove the tab event as I'm unhappy with the implementation.
Materialize `onShow` function has a parameter which points to the current tab element while the bridge event only has the element's `id` value.

While I think passing the element is better, implementing this introduces a breaking change for current users.

I've implemented a call handler instead:
```html
<ul md-tabs="on-show.call: onShow(element)" md-on-selected.delegate="onTabSelected($event)" class="z-depth-1">
  ...
</ul>
```

**Comment by a2345sooted** [comment]
Hi,

Is there any update to the modal functionality changes?

I'm having trouble getting this to work.  I've switched over to the Aurelia CLI installation on a new project, but I'm unable to successfully run:

`$(this.myModal).modal( );`
or
`$(this.myModal).openModal( );`

here is what the modal looks like in the html template:
```
<div id="logout-modal" class="modal" ref="myModal">
      <h5>Some modal content</h5>
  </div>
```

I have a button that when clicked, runs:
`$(this.myModal).modal( );`
but nothing at all happens.  If I use
`$(this.myModal).openModal( );`

I get that openModal() is not a function.

I followed the installation instructions for the CLI step by step and everything is building ok and everything else seems to be working so far. I have tried installing different versions of jquery, but that hasn't worked.  

I read somewhere about jquery needing to run before the aurelia bootstrapper starts... is there a step I should be adding that's not in the installation docs?

Thanks,
Robert

**Comment by Thanood** [comment]
Hi Robert,

I tried to create a gist to check/demonstrate but I noticed my gist bundles are broken and still use an older version.. I'll create a separate issue to not forget updating them. Unfortunately we have to be kind of "blind" now.. :smiley: 

Are there any errors logged to the console?

As for jQuery versions, anything below jQuery 3 should do.
And if `$(this.myModal).modal( );` doesn't throw any error then jQuery and Materialize seem to be loaded.

I didn't have any problems here: http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/modals

What I see immediately from your post is that you didn't use the `md-modal` attribute. It initializes the modal. Also the `ref` should actually reference that attribute, so `md-modal.ref="myModal"` would be correct. The `openModal()` function is in there.

The sample linked above used this in the same way. :smiley: 

Regards,
Daniel

**Comment by a2345sooted** [comment]
Thanks for your help Daniel.  I got it working now. 

openModal() is still not a function though... maybe I'm still doing something wrong. 

What is working for me now is:

`<div id="modal1" md-modal md-modal.ref="logoutModal"> ....`

and in VM:

`this.logoutModal.open();`

**Comment by a2345sooted** [comment]
frankly though, I seemingly looked everywhere but the modal docs... looks like they've been updated since last time I used this plugin... Awesome work man

**Comment by Thanood** [comment]
Well, `openModal` is completely gone from Materialize.
They changed their modal api and introduced a breaking change with that. It's now just `modal` on the element itself while `openModal` was used on the trigger.

IMO that's better but there's a lot on confusion about this change (which is completely understandable).

**Comment by a2345sooted** [comment]
i'm also getting these non-fatal errors on my page load:

```
GET http://localhost:9000/materialize-css/fonts/roboto/Roboto-Thin.ttf 
GET http://localhost:9000/materialize-css/fonts/roboto/Roboto-Thin.woff 
GET http://localhost:9000/materialize-css/fonts/roboto/Roboto-Thin.woff2 
```

I'm using the Aurelia CLI.  Any ideas what this might be?

**Comment by Thanood** [comment]
Yep. Have a look here for details: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/284

Basically, as the fonts' path is set in `materialize.css`, after bundling fonts are not where the css expects them (that would be relative to the bundle). A solution is to copy the fonts to the location where they are expected.

Another approach is to copy the css to a location where the fonts are relative to the css file and not load the bundle.

Fonts are not(yet) bundled in an Aurelia CLI bundle.
