### ISSUE TITLE
md-label on md-input not rendered good in Safari (and mobile)

### ISSUE THREAD

**Issue by Ganbin** [aurelia-ui-toolkits/aurelia-materialize-bridge#309]
Hello,

I have a formular with many fields (switch, datepicker, select, input, textarea), everything works well. When I try to see this form on my iphone device, I get 3 fields where the labels are push to the right outside of the fields.

I have figure out that's only the labels which are set inside of `md-input` with `md-label`. I send you the code to reproduce with gist.run, but gist.run doesn't run on iphone device. So I think you must do it yourself to reproduce the issue.

To change the window size of the desktop browser doesn't reproduce the issue, neither the iphone simulator of google chrome.

[Here is the code](https://gist.run/?id=483b7b22e22d3714a5880de0a425a26e)

**Comment by Thanood** [comment]
Hey @Ganbin 😃 
Can you attach a screenshot of how it looks on an iPhone? That would help me a little as I don't have direct access to an iPhone. I will have to ask one of my co-workers tomorrow.

Any idea if this happens on a desktop Safari?

**Comment by Ganbin** [comment]
Actually you are right. This happens in my desktop Safari browser too.

**Comment by Ganbin** [comment]
I have change the Title because I think it is more an issue relative to Safari...

**Comment by Thanood** [comment]
Is this related?
https://github.com/Dogfalo/materialize/issues/3789

**Comment by Ganbin** [comment]
Ok i will try to figure out when i will be on my computer. Thanks for the link

**Comment by Ganbin** [comment]
SO I have made some test. As said in the thread you point me out : 

> @dapplebeforedawn You need to use "row" and "col" classes for the fields as in the MaterializeCSS docs example - http://materializecss.com/forms.html

```
<div class="container">
  <form>
    <div class="row">
      <div class="input-field col s12">
        <input id="comment" name="comment"><label for="comment">broken</label></div>
      </div>
    </div>
  </form>
</div>
```

Because the aurelia-materialize-bridge will create the html stucture itself, the `input-field` class will be in a different level than the `col s12` `div`, I have made the test to add the `input-field` and `col s12` in the same `div` and it fix the issue. BUT, this will end up to chain 2 `input-field` class which will imply than the `input` will have 2 time the `margin-top: 1rem` which will cause an alignement issue.

So what are the possibility to avoid this. Should we consider that an `md-input` will always be wrap up in a `row>col` elements and then we should add the `input-field` and the we should add the input-field to the parent element which have a `col` class. But I think this imply too much complication.

Another idea I have is too just avoid the addition of the `input-field` class on the composed element made by the bridge and let the user have control on the class he want to use.

What do you think?

**Comment by Ganbin** [comment]
If we look at the materialize documentation, the `input-field` is always coupled with the `col` class, except for an inline field.

**Comment by Ganbin** [comment]
In this issue (https://github.com/Dogfalo/materialize/issues/3822) we can see that they came to the same conclusion : 

> @kmmbvnr Yes you are correct, this is occurring when not using .row .col tags. The reason is because I prefer to use a custom grid made with Susy 2, rather than the premade grid in materialize. In that case, I have no need for the .row .col tags since my grid handles it.

**Comment by Thanood** [comment]
Honestly, I think this sounds more like a workaround than a solution.
What exactly does `col s12` in a `row` really do to the input label? We should try and reproduce that.

I'm not against changing the structure of the template or even making it a custom attribute instead of an element, which resides on the input. It's just that "put a grid around the input" doesn't sound like very good solution.

(This was before you posted your last two comments..)

**Comment by Ganbin** [comment]
No to make it a custom attribute element doesn't sounds good.

But maybe to let the user have control of the `input-field` class could be a solution. But again, if the user use a different grid system than the one from materialize, it could be a problem. Like the https://github.com/Dogfalo/materialize/issues/3822 issue.

**Comment by Ganbin** [comment]
This sound's like a materialize issue that the bridge depend on...

**Comment by kmmbvnr** [comment]
Just upgrade to  0.97.8. The issue is already fixed

**Comment by Thanood** [comment]
@kmmbvnr
That would be nice indeed. :smiley: 

Anyway, I'll try to find it in the commit log or issues to learn more about it.

@Ganbin 
I must be missing something. You have this in your sample gist:

```html
<div class="row">
  <div class="input-field col s12">
    <input id="comment" name="comment"><label for="comment">broken</label></div>
  </div>
</div>
```

Did you change that? Because that can't be the "broken" one then, right?
It's okay, I'd just like to know. :smiley:

**Comment by Thanood** [comment]
@kmmbvnr
Found your issue comment. :wink: 

Commit seems to be here:
https://github.com/Dogfalo/materialize/commit/28b119a8233280e927318f8b02051a6f69ff65cf

@Ganbin Please try with the current gist (updated yesterday). It uses 0.97.8:
https://gist.run/?id=e8eed34e8bba17f5213535bcdd004a9e

**Comment by Thanood** [comment]
Checked in FF and could probably reproduce it with the textarea (still don't have a screenshot from safari mac :wink: )..

Updating to the current bridge/materialize version solved it at least there:
https://gist.run/?id=efaf578e706f1aa0d68faf3cad79c51e

(it's a fork of your gist with the current bundle version)

**Comment by Ganbin** [comment]
@Thanood Actually I was quoting @kmmbvnr at https://github.com/Dogfalo/materialize/issues/3789#issuecomment-256536220

**Comment by Ganbin** [comment]
the 0.97.8 don't have the `js/leanModal.js` file which make my `rbuild.js` to fail because I'm in a CLI environnement... I can never do something simple... So Now I don't have more time I will try to look this afternoon.

**Comment by Thanood** [comment]
> @Thanood Actually I was quoting @kmmbvnr at Dogfalo/materialize#3789 (comment)

Sorry, I didn't get that. This week is just confusing as a whole and today is no different..

I've uploaded the changed CLI files (rbuild.js, materialize-css.js) yesterday here:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/tree/master/build/tools

Or, just replace `leanModal` with `modal` in these two files.
Maybe, if you have some time, could you check the gist on Safari?

**Comment by Thanood** [comment]
> @Thanood Actually I was quoting @kmmbvnr at Dogfalo/materialize#3789 (comment)

Sorry, I didn't get that. This week is just confusing as a whole and today is no different..

I've uploaded the changed CLI files (rbuild.js, materialize-css.js) yesterday here:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/tree/master/build/tools

Or, just replace `leanModal` with `modal` in these two files.
Maybe, if you have some time, could you check the gist on Safari?

**Comment by Thanood** [comment]
I could probably make the `class` attribute of the native input bindable.
Also a good idea for `inline` text fields.

**Comment by Ganbin** [comment]
Gist doesnt run on safari because safari doesnt support service worker. Ill try on my project when im back in my conputer.

**Comment by Ganbin** [comment]
By the grace of God it is working well with the update of materialize and the bridge (https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/309#issuecomment-258390038).

Thanks a lot agin for the help.

**Comment by Thanood** [comment]
Yay! :sparkles:
